version: '3'

services:
  server:
      build: ./server
      ports:
        - "80:80"
      links:
        - website
      volumes:
        - ./server/nginx.conf:/etc/nginx/nginx.conf

        - ./server/access.log:/var/log/nginx/access.log
        - ./server/error.log:/var/log/nginx/error.log

  webservice:
      build: ./webservice
      ports:
        - 5001:80
      volumes:
        - ./webservice:/usr/src/app

  website:
      build: ./website
      volumes:
        - ./website/src:/usr/share/nginx/html
      ports:
        - "9000:9000"
      depends_on:
        - webservice
