version: '3'

services:
  server:
      build: ./server
      ports:
        - "80:80"

  webservice:
      build: ./webservice
      ports:
        - "5001:80"

  website:
      build: ./website
      ports:
        - "9000:9000"
